# Compiler
CC = gcc

# Compiler flags
CFLAGS = -O2

# Source files (only your program)
SRCS = main.c sqlite3.c

# Object files
OBJS = $(SRCS:.c=.o)

# Executable name
TARGET = main

# Default target
all: $(TARGET)

# Link the object files to create the executable
$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJS) $(LDFLAGS)

# Compile source files into object files
%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

# Clean up build files
clean:
	del /F /Q $(OBJS) $(TARGET).exe 2> NUL || exit 0


# Phony targets (not actual files)
.PHONY: all clean